// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FirewallUIClient is the client API for FirewallUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirewallUIClient interface {
	// ListEngineSpecs returns a list of Firewall Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (FirewallUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type firewallUIClient struct {
	cc grpc.ClientConnInterface
}

func NewFirewallUIClient(cc grpc.ClientConnInterface) FirewallUIClient {
	return &firewallUIClient{cc}
}

func (c *firewallUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (FirewallUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &FirewallUI_ServiceDesc.Streams[0], "/v1.FirewallUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &firewallUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FirewallUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type firewallUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *firewallUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *firewallUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.FirewallUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirewallUIServer is the server API for FirewallUI service.
// All implementations must embed UnimplementedFirewallUIServer
// for forward compatibility
type FirewallUIServer interface {
	// ListEngineSpecs returns a list of Firewall Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, FirewallUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedFirewallUIServer()
}

// UnimplementedFirewallUIServer must be embedded to have forward compatible implementations.
type UnimplementedFirewallUIServer struct {
}

func (UnimplementedFirewallUIServer) ListEngineSpecs(*ListEngineSpecsRequest, FirewallUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedFirewallUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedFirewallUIServer) mustEmbedUnimplementedFirewallUIServer() {}

// UnsafeFirewallUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirewallUIServer will
// result in compilation errors.
type UnsafeFirewallUIServer interface {
	mustEmbedUnimplementedFirewallUIServer()
}

func RegisterFirewallUIServer(s grpc.ServiceRegistrar, srv FirewallUIServer) {
	s.RegisterService(&FirewallUI_ServiceDesc, srv)
}

func _FirewallUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FirewallUIServer).ListEngineSpecs(m, &firewallUIListEngineSpecsServer{stream})
}

type FirewallUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type firewallUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *firewallUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FirewallUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FirewallUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FirewallUI_ServiceDesc is the grpc.ServiceDesc for FirewallUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirewallUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FirewallUI",
	HandlerType: (*FirewallUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _FirewallUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _FirewallUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "firewall-ui.proto",
}
